apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: triggerflow-worker
  #namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      #containerConcurrency: 1
      #timeoutSeconds: 300
      containers:
        - image: jsampe/triggerflow-worker
          env:
          - name: KAFKA_TOPIC
            value: 'workspace-topic'
          resources:
            limits:
              memory: 2Gi
              cpu: 2
