triggerflow:
  endpoint: <API_ENDPOINT>
  user: <USER>
  password: <PASSWORD>

dags:
  operators:

    ibm_cf:
      endpoint: <ENDPOINT_URL>
      namespace: <NAMESPACE>
      api_key: <API_KEY>
      event_source: <EVENT_SOURCE_NAME>
      kafka:
        broker_list: []
      rabbitmq:
        amqp_url: <AMQP_URL>
      redis:
        host: <REDIS_HOST>
        port: 6379
        password: <REDIS_PASSWORD>
        db: 0

    aws_lambda:
      access_key_id: <ACCESS_KEY_ID>
      secret_access_key: <SECRET_ACCESS_KEY>
      region_name: <REGION_NAME>

statemachines:
  aws:
    access_key_id: <ACCESS_KEY_ID>
    secret_access_key: <SECRET_ACCESS_KEY>
    region_name: <REGION_NAME>