triggerflow_controller:
   endpoint: <API_ENDPOINT>

cloudant:
   cloudant_user: <USERNAME>
   auth_token: <PASSWORD>
   url: <SERVICE_URL>

redis:
   host: <HOST>
   port: <PORT>
   password: <PASSWORD>


