triggerflow:
  endpoint: <API_ENDPOINT>
  user: <USER>
  password: <PASSWORD>

dags:
  operators:
    ibm_cf:
      endpoint: <ENDPOINT_URL>
      namespace: <NAMESPACE>
      api_key: <API_KEY>
      event_source: <TERMINATION_EVENT_DESTINATION>
      kafka:
        broker_list: []
      rabbitmq:
        amqp_url: <AMQP_URL>
      redis:

    aws_lambda:
      access_key_id: <ACCESS_KEY_ID>
      secret_access_key: <SECRET_ACCESS_KEY>
      region_name: <REGION_NAME>

statemachines:
  aws:
    access_key_id: <ACCESS_KEY_ID>
    secret_access_key: <SECRET_ACCESS_KEY>
    region_name: <REGION_NAME>