triggerflow:
    endpoint: <API_ENDPOINT>
    user: <USER>
    password: <PASSWORD>

ibm_cf:
    endpoint  : <ENDPOINT>
    namespace : <NAMESPACE>
    api_key   : <APIKEY>

rabbitmq:
    amqp_url: <AMQP_URL>

kafka:
    broker_list: <BROKER_LIST>
    user: <USER>
    password: <PASSWORD>
  
redis:
    host: <HOST>
    port: <PORT>
    password: <PASSWORD>


