apiVersion: apps/v1
kind: Deployment
metadata:
  name: triggerflow-keda-controller
spec:
  selector:
    matchLabels:
      app: triggerflow-keda-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: triggerflow-keda-controller
    spec:
      containers:
      - name: triggerflow-keda-controller
        image: triggerflow/triggerflow-keda-controller
        ports:
        - containerPort: 8080
        resources:
            limits:
              memory: 512Mi
              cpu: 1000m
        env:
          - name: TRIGGERFLOW_STORAGE_BACKEND
            value: redis
          - name: REDIS_HOST
            value: {REDIS_HOST}
          - name: REDIS_PASSWORD
            value: {REDIS_PASSWORD}
          - name: CREATE_ADMIN_USER
            value: yes
---
apiVersion: v1
kind: Service
metadata:
  name: triggerflow-keda-controller
  labels:
    run: triggerflow-keda-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: triggerflow-keda-controller
