apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: triggerflow-controller
  #namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      timeoutSeconds: 30
      containers:
        - image: jsampe/triggerflow-controller
          resources:
            limits:
              memory: 256Mi
              cpu: 0.5
