apiVersion: messaging.knative.dev/v1alpha1 
kind: Subscription
metadata:
  name: triggerflow-sub-imc
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: triggerflow-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: triggerflow-worker-pywren
---
apiVersion: messaging.knative.dev/v1alpha1 
kind: Subscription
metadata:
  name: triggerflow-sub-kc
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: triggerflow-kafka-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: triggerflow-worker-pywren